
- name: Delete MySQL Deployment
  k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mysql-service
        namespace: "{{ namespace }}"

- name: Delete MySQL PVC
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mysql-pv-claim
        namespace: "{{ namespace }}"

- name: Delete MySQL Service
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: mysql-service
        namespace: "{{ namespace }}"